{
 "title": "Finance Dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "granularity",
    "label": "Granularity",
    "query": "YEAR, MONTH, DAY, QUARTER, WEEK"
   },
   { "name": "patch" }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total_income AS (\n    SELECT \n        SUM(amount) AS total_income\n    FROM \n        transactions\n    WHERE \n        amount > 0\n        AND date BETWEEN $__timeFrom() AND $__timeTo()\n        AND internal = false\n),\ntotal_expenses AS (\n    SELECT \n        SUM(amount) AS total_expenses\n    FROM \n        transactions\n    WHERE \n        amount < 0\n        AND date BETWEEN $__timeFrom() AND $__timeTo()\n        AND internal = false\n),\nexpenses_by_class AS (\n    SELECT \n        classification,\n        ABS(SUM(amount)) AS total_amount\n    FROM \n        transactions\n    WHERE \n        amount < 0\n        AND date BETWEEN $__timeFrom() AND $__timeTo()\n        AND internal = false\n    GROUP BY \n        classification\n    HAVING \n        SUM(amount) <> 0\n)\nSELECT \n    classification,\n    total_amount\nFROM \n    expenses_by_class\nUNION ALL\nSELECT \n    'Free Income' AS classification,\n    (SELECT total_income FROM total_income) + (SELECT total_expenses FROM total_expenses) AS total_amount\nORDER BY \n    total_amount DESC;"
    }
   ]
  },
  {
   "title": "Expenses by class",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('${granularity}', date) AS period,\n    /* Drop something in the concat clause if the colors aren't as distinguishable */\n    CASE WHEN classification IS NULL THEN 'n/a' ELSE CONCAT('', classification) END AS classification,\n    ABS(SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END)) AS Expense\nFROM \n    transactions\nWHERE \n    date BETWEEN $__timeFrom() AND $__timeTo() AND not internal\nGROUP BY \n    DATE_TRUNC('${granularity}', date), classification\nORDER BY \n    period, Expense;"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 22, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  hash,\n  date,\n  description,\n  amount,\n  currency,\n  classification,\n  CASE\n    WHEN internal AND amount < 0 THEN 'Internal Transfer'\n    WHEN internal AND amount >= 0 THEN 'Internal Transfer'\n    WHEN NOT internal AND amount < 0 THEN 'Expense'\n    WHEN NOT internal AND amount >= 0 THEN 'Income'\n  END AS type,\n  'Change' AS link\nFROM\n  transactions\nWHERE\n  date BETWEEN $__timeFrom()\n  AND $__timeTo()\nORDER BY\n  date DESC;"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH RECURSIVE date_series AS (\n    SELECT DATE_TRUNC('${granularity}', $__timeFrom()::DATE) AS date\n    UNION ALL\n    SELECT DATE_TRUNC('${granularity}', (date + INTERVAL '1 ${granularity}')::DATE)\n    FROM date_series\n    WHERE date < DATE_TRUNC('${granularity}', $__timeTo()::DATE)\n),\nlast_balance AS (\n    SELECT\n        iban,\n        DATE_TRUNC('${granularity}', date) AS date,\n        balance,\n        ROW_NUMBER() OVER (PARTITION BY iban ORDER BY date DESC) AS rn\n    FROM transactions\n),\ninterpolated_balances AS (\n    SELECT\n        ds.date,\n        t.iban,\n        COALESCE(\n            (SELECT balance FROM last_balance lb WHERE lb.iban = t.iban AND lb.date <= ds.date ORDER BY lb.date DESC LIMIT 1),\n            0\n        ) AS balance\n    FROM\n        date_series ds\n    CROSS JOIN\n        (SELECT DISTINCT iban FROM transactions) t\n)\nSELECT\n    date,\n    iban,\n    balance\nFROM\n    interpolated_balances\nWHERE\n    date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY\n    date, iban;"
    }
   ]
  },
  {
   "title": "Income / Expenses",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('${granularity}', date) AS period,\n    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS Income,\n    -SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS Expenses,\n    SUM(amount) AS FreeIncome\nFROM \n    transactions\nWHERE \n    date BETWEEN $__timeFrom() AND $__timeTo()\n    AND internal = false\nGROUP BY \n    DATE_TRUNC('${granularity}', date)\nORDER BY \n    period;"
    }
   ]
  },
  {
   "title": "Average spendings per month and running month based on end date",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH avg_monthly_spend AS (\n  SELECT \n    classification, \n    ABS(SUM(amount)) / NULLIF(DATE_PART('month', AGE($__timeTo()::timestamp, $__timeFrom()::timestamp)), 0) AS avg_amount_per_month\n  FROM transactions\n  WHERE\n    amount < 0\n    AND date BETWEEN $__timeFrom() AND $__timeTo()\n    AND internal = false\n  GROUP BY classification\n),\ncurrent_month_spend AS (\n  SELECT \n    classification, \n    ABS(SUM(amount)) AS current_month_amount\n  FROM transactions\n  WHERE\n    amount < 0\n    AND date BETWEEN DATE_TRUNC('month', $__timeTo()::timestamp) AND $__timeTo()::timestamp\n    AND internal = false\n  GROUP BY classification\n)\nSELECT \n  COALESCE(cms.classification, ams.classification) AS classification, \n  ams.avg_amount_per_month AS avg,\n  cms.current_month_amount AS spent\nFROM current_month_spend cms\nFULL OUTER JOIN avg_monthly_spend ams ON cms.classification = ams.classification\nORDER BY avg DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Expected transactions",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT \n  description, amount, currency, rhythm,\n  'in ' || (expected::date - $__timeTo()) || ' days' AS expected_in,\n  expected\nFROM transactions \nWHERE expected > $__timeTo() \nORDER BY expected;"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Finance Dashboard",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN '$patch' = 'successful' THEN 'Transaction(s) updated successfully!'\n    ELSE 'If some of the transactions listed below are not classified correctly, you can click on the links in the table to change the classification. If you redeploy the app and dont see your previous changes, you can replay the patches you made:'\n  END AS msg,\n  CASE\n    WHEN '$patch' = 'successful' THEN 1\n    ELSE 0\n  END AS val\nFROM\n  transactions\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "[Click here to apply patched transactions](http://localhost:3001/apply-patches)"
   }
  }
 ]
}